Added log only if signature match
ctsit/report_handler pull request #10
Opened 2023-06-14 20:56 UTC by sinarest1608

Added check if "report_handler" present.

Should be merged before #9

2023-06-27 20:25 UTC, mbentz-uf requested changes
The behavior of the package has changed since migrating from python_db_logger, but the code hasn't been updated to reflect the change in behavior. I didn't notice until reviewing the code further that we can get rid of `add_log_entries`, `build_default_extras`, and simplify the logic to flow be more straightforward. The refactor looks like:

```python
def emit(self, record):
    # Only process if report_handler key is present
    if "report_handler" not in record.__dict__.keys():
        return

    if not hasattr(self, "start_time"):
        self.start_time = datetime.utcnow()

    # Add entry to levelname
    self.add_entry_to_sheet(sheet=record.levelname, entry=_clean_record_msg(record.msg))

    entry, sheet = utils.retrieve_data_and_sheet_name(
        record.__dict__["report_handler"])

    # Add to additional sheet if specified
    if (sheet):
        self.add_entry_to_sheet(sheet=sheet, entry=entry)

def _clean_record_msg(raw_msg: string): 
    cleaned_log_msg = raw_msg
    cleaned_log_msg = cleaned_log_msg.strip()
    cleaned_log_msg = cleaned_l
```

2023-06-29 16:26 UTC, sinarest1608 reviewed
@mbentz-uf 
The 
```python
if "report_handler" in record.__dict__.keys():
``` 
was done to accommodate handlers like Kafka and sql in future. New change looks like this:

```python
    def emit(self, record):
        # Only process if report_handler key is present
        # if "report_handler" not in record.__dict__.keys():
        #     return

        if not hasattr(self, "start_time"):
            self.start_time = datetime.utcnow()

        if "report_handler" in record.__dict__.keys():
            # Add entry to levelname
            self.add_entry_to_sheet(sheet=record.levelname,
                                    entry=self._clean_record_msg(record.msg))

            entry, sheet = utils.retrieve_data_and_sheet_name(
                record.__dict__["report_handler"])

            # Add to additional sheet if specified
            if (sheet):
                self.add_entry_to_sheet(sheet=sheet, entry=entry)

    def _clean_record_msg(self, raw_msg: str):
        cleaned_log_msg = raw_msg
        cleaned_log_msg = cleaned_log_msg.strip()
        return cleaned_log_msg
```
Another change which had to be done to accommodate the above was replacing 
```python
headers, values = itemgetter("headers", "values")(row_data)
```
 by 
```python
headers, values = utils.get_headers_and_content(row_data)
``` 
in `write_report` function because write report now supports adding logs using an array of objects.

Should I proceed and commit this change?

2023-06-29 17:24 UTC, mbentz-uf commented
> was done to accommodate handlers like Kafka and sql in future
I'm not sure what you mean, that is what checking for "report_handler" at the top of the emit function does. Unless that key exists then we do nothing in the emit function and return, otherwise we continue.

2023-06-29 18:18 UTC, sinarest1608 commented
I think I misunderstood your comment. I had the picture in mind that we plan to integrate other handlers in this project itself. 
I will add the suggested changes and push to the branch.

2023-06-30 14:01 UTC, mbentz-uf commented
@sinarest1608 Can you include the changes from PR #9 in this PR? It should be easier to test that way.

2023-06-30 14:05 UTC, sinarest1608 commented
@mbentz-uf 
Should I add all the tests here itself and discard the PR #9 branch?

2023-06-30 14:17 UTC, mbentz-uf commented
Yes that would be great!

2023-06-30 15:14 UTC, sinarest1608 commented
@mbentz-uf Added the fixed tests.

2023-07-05 13:23 UTC, mbentz-uf commented
The latest commit wouldn't show on the PR until I changed the base branch to main and back to develop.

2023-07-05 13:58 UTC, mbentz-uf requested changes
Separate unit test into multiple tests to cover each test case.

2023-07-07 14:58 UTC, sinarest1608 commented
@mbentz-uf 
I have separated the tests into different functions.

2023-07-07 18:10 UTC, mbentz-uf commented on tests/report_handler/test_report_handler.py
> +
Can you remove these comments?

2023-07-07 18:18 UTC, sinarest1608 commented on tests/report_handler/test_report_handler.py
> +
@mbentz-uf 
Done!

2023-07-07 18:58 UTC, mbentz-uf commented
Can you take a look at the unit tests? They are failing.

2023-07-07 19:04 UTC, sinarest1608 commented
@mbentz-uf 
All the tests work perfectly fine for me when I run them in VsCode or from the command line. Seems like automated workflows are failing due to missing optional packages. The log file for every test function is deleted after the function is completed, which might not be happening due to the optional dependencies resulting in extra elements. 
```python
======================================================================
FAIL: test_log_file (tests.report_handler.test_report_handler.TestReportHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/report_handler/report_handler/tests/report_handler/test_report_handler.py", line 113, in test_log_file
    self.assertEqual(log_sequence_expected, log_sequence)
AssertionError: Lists differ: ['INFO', 'DEBUG', 'WARNING', 'ERROR'] != ['DEBUG', 'DEBUG', 'DEBUG', 'DEBUG', 'INFO', 'DEBUG', 'WARNING', 'ERROR']

First differing element 0:
'INFO'
'DEBUG'

Second list contains 4 additional elements.
First extra element 4:
'INFO'

- ['INFO', 'DEBUG', 'WARNING', 'ERROR']
+ ['DEBUG', 'DEBUG', 'DEBUG', 'DEBUG', 'INFO', 'DEBUG', 'WARNING', 'ERROR']

----------------------------------------------------------------------
```
I will try adding them to `pyproject.toml` and check if they work.

2023-07-07 19:07 UTC, sinarest1608 commented
@mbentz-uf 
That worked!

2023-07-10 15:36 UTC, merged