Added report writing from array of entries
ctsit/report_handler pull request #11
Opened 2023-06-16 19:48 UTC by sinarest1608

This adds the functionality of logging to report using an array of entries. Also added the Unit tests. 

Refer #7 

To Review:
Check the code flow and verify that the unit tests are passed.

Note: It would be better to merge #9 and #10 before merging this.

2023-07-10 16:10 UTC, sinarest1608 commented
@mbentz-uf 

The lint workflow outputs the following E226 errors:
```python
./tests/report_handler/test_report_handler.py:59:47: E226 missing whitespace around arithmetic operator
./tests/report_handler/test_report_handler.py:66:35: E226 missing whitespace around arithmetic operator
./tests/report_handler/test_report_handler.py:76:47: E226 missing whitespace around arithmetic operator
./tests/report_handler/test_report_handler.py:91:35: E226 missing whitespace around arithmetic operator
```
But the file `./tests/report_handler/test_report_handler.py` does not exists on this branch. 
I fixed E226 on other files present on this branch in the previous commit.

2023-07-10 18:25 UTC, mbentz-uf requested changes
Please rewrite the function to add entries to the internal `log` variable and remove path from the function signature. To generate the xlsx `write_report` would still need to be called.

2023-07-10 18:25 UTC, mbentz-uf commented on src/report_handler/report_handler.py
> +            return Exception("Data signature mis-match! Data should have 'headers' and 'rows'")
Small typo, should be mismatch instead.

2023-07-10 18:25 UTC, mbentz-uf commented on src/report_handler/report_handler.py
> +            f"{path}/rejected-publications-report-{datetime.today().strftime('%Y-%m-%d')}.xlsx")
I didn't do a good job explaining this in the issue. The function `add_to_sheet` is meant to add entries to the internal `log` variable (use `add_entry_to_sheet`), not to generate a separate xlsx. The code snippet I included in the example, is an example of how we will incorporate the new feature into ufvivo_pubingest.

2023-07-25 18:40 UTC, mbentz-uf commented
Do the tests show up for you in VSCode?

2023-07-25 18:41 UTC, sinarest1608 commented
@mbentz-uf 
I can't see the tests in VsCode. I remember using command line to run the tests.

2023-07-25 18:44 UTC, mbentz-uf commented
Can you help me look into that? Removing the -s flag from `settings.json` fixes it but we use that flag for all of our other python projects. This is what the Output>Python:

![image](https://github.com/ctsit/report_handler/assets/75623654/56720ce1-70b8-4e9f-b8d4-9e6d660f9d72)

2023-07-25 18:54 UTC, sinarest1608 commented
Changing the next argument after `-s` to `.` fixed this. 

```python
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        ".",
        "-p",
        "*test*.py"
    ],
```

2023-07-25 20:14 UTC, mbentz-uf approved these changes

2023-07-25 20:15 UTC, mbentz-uf commented
Looks good, thanks for the help with this!

2023-07-25 20:15 UTC, merged